version: '3.8'
services:
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://db/pasargad
    depends_on:
      - db
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - pasargad:/data/db
volumes:
  pasargad:
